//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intersel_Practica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallDetail
    {
        public string CallDetailId { get; set; }
        public string MobileLine { get; set; }
        public string CalledPartyNumber { get; set; }
        public string CalledPartyDescription { get; set; }
        public string DateTime { get; set; }
        public string Duration { get; set; }
        public string TotalCost { get; set; }
    }
}
